jms_serializer:
  handlers:
    datetime:
      default_format: 'Y-m-d\TH:i:sO'
      default_timezone: 'UTC'
  property_naming:
    id: jms_serializer.identical_property_naming_strategy
  visitors:
    xml_serialization:
      format_output: '%kernel.debug%'
