version: '3.4'

services:
    php:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        volumes:
            - .:/var/www:delegated
        working_dir: /var/www
        command: php-fpm
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        ports:
            - "9000:9000"
        container_name: cs-php

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:alpine
        ports:
            - "8888:80"
        volumes:
        - .:/var/www:delegated
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
        links:
            - php
        container_name: cs-nginx

volumes:
    db_data: {}
