services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Persistence\MemoryCartRepository:
        autowire: true
        public: true

    App\Application\CommandHandler\AddProductCommandHandler:
        tags: ['messenger.message_handler']

    App\Application\CommandHandler\RemoveProductCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\Application\QueryHandler\GetCartQueryHandler:
        tags: ['messenger.message_handler']

    App\Domain\Discount\EveryFifthProductFreeStrategy:
        tags: ['discount.strategy']

    App\Domain\Discount\PercentageDiscountStrategy:
        tags: ['discount.strategy']

    App\Application\Service\DiscountManager:
        arguments:
            $strategies: !tagged_iterator discount.strategy

